<!-- # 读取数据 -->
```{r}
load("model1_phase1_ICdata.RData")

# 长数据
N = length(model1.icdata$tlist)
dataWarping = c()
for (i in 1:N) {
  dataWarping = rbind(dataWarping,
                      cbind(model1.icdata$dayslist[[i]],
                            model1.icdata$tlist[[i]],
                            model1.icdata$xlist[[i]],
                            model1.icdata$ylist[[i]]))
}
dimnames(dataWarping)[[2]] = c("day","time","x","y")
dataWarping = as.data.frame(dataWarping)
dataWarping$index = (1:nrow(dataWarping))

time = dataWarping$time
days = unique(dataWarping$day)
y = dataWarping$y
x = dataWarping$x
n = nrow(dataWarping)
```
<!-- # 拟合变系数的混合效应模型,方差未知的情况，使用LME() -->
```{r}
# X中包含X.gaussian,Z为block
# mod estimate
# X
X.fixed = cbind(1,time)
dimnames(X.fixed)[[2]] = NULL
# Z.overall
K = 10
knots = quantile(unique(time),seq(0,1,length = K+2))[-c(1,K+2)]
Z.overall <- outer(time, knots, "-")
Z.overall <- Z.overall*(Z.overall > 0)
dimnames(Z.overall)[[2]] = NULL

X.gaussian = Z.overall
X = cbind(X.fixed,X.gaussian)*dataWarping$x

Z.subject = X 
dummy <- as.factor(dataWarping$day)
library(nlme)
mod.lme <- lme(y~-1+X, random=list(dummy=pdIdent(~Z.subject-1)))
summary(mod.lme)
# Z分块Z.block，为后面C矩阵计算做准备
# 每个子Z.block 对应的id
indexlist = vector("list",N)
for (i in 1:N) {
  indexlist[[i]] = which(dataWarping$day %in% days[i])
}

Z.block = c()
for (i in 1:N) {
  operator = rep(1,n)*0
  operator[indexlist[[i]]] = 1
  Z.fixed = X.fixed*operator
  Z.gaussian = Z.overall*operator
  Z.block = cbind(Z.block,Z.fixed,Z.gaussian)
}
Z.block = Z.block * dataWarping$x

# parameters hat
beta <- fixef(mod.lme)
u <- ranef(mod.lme)
sig.sq <- mod.lme$sigma^2

# fit value
f.fixed = X[1:197,] %*% t(t(beta))
plot(dataWarping$time[1:197],f.fixed)

f.fixed = X %*% t(t(beta))
fv = cbind(dataWarping$day,dataWarping$time,f.fixed,fitted(mod.lme))
dimnames(fv)[[2]] = c("day","time","f.fixed","fv")
fv = as.data.frame(fv)

# fv = fitted(mod.lme)
plot(fv$time[indexlist[[1]]],fv$f.fixed[indexlist[[1]]],type = 'l',col="red",lwd=1,ylim = c(-5,5))
for (i in 1:1) {
  lines(fv$time[indexlist[[i]]],fv$fv[indexlist[[i]]],type = 'o',col="red",lwd=1,cex = 0.5)
  lines(fv$time[indexlist[[i]]],y[indexlist[[i]]],type = 'l',col="black",lwd=1)
}

# uhat的协方差矩阵D
D = getVarCov(mod.lme)
```
<!-- 利用估计的模型，计算固定效应系数函数、随机效应协方差函数，以及误差项的方差 
time：时间间隔为最小间隔，为了在phase II 后续能够快速提取信息-->
```{r}
# 时间time，设定间隔为0.001
time = seq(0,1000,by = 1)

# X:固定效应的系数函数的模型矩阵
X.fixed = cbind(1,time)
dimnames(X.fixed)[[2]] = NULL
# Z.overall
K = 10
knots = quantile(unique(time),seq(0,1,length = K+2))[-c(1,K+2)]
Z.overall <- outer(time, knots, "-")
Z.overall <- Z.overall*(Z.overall > 0)
dimnames(Z.overall)[[2]] = NULL

X.gaussian = Z.overall
X = cbind(X.fixed,X.gaussian)
Z = X
# 固定效应的系数函数
coef.fixed = X %*% fixef(mod.lme)
plot(coef.fixed,cex = 0.5)

# 随机效应系数函数的协方差函数矩阵 r(s,t),r.mat
r.mat = Z %*% getVarCov(mod.lme) %*% t(Z)
```

<!-- 用于5000次仿真计算 -->
<!-- ARL和ATS 计算 -->
```{r}
source("E:\\zhangwei\\Rprogram\\In profile monitoring\\basic functions for data generate.R")
source("E:\\zhangwei\\Rprogram\\In profile monitoring\\basic funcitons for 1 covariate with LPK and ewma.R")
library(MASS)

epsilon4 = 3; h = 0.1
# 失控ATS的偏移大小
case.n = 1
lambda = 0.2
deltalist = c(0.05,0.1,0.2,0.4,0.5)
deltalist = c(0.5)
# datalist = OCdata.case3(rate = 1,N = 1,tc.end = 1000,delta=0.5)
# plot(datalist$ylist[[1]],type = "l")
```

<!-- ATS1 5000次 -->
```{r}
library(parallel)
library(doParallel)
library(foreach)
no_cores = detectCores()
registerDoParallel(makeCluster(no_cores))

Nouter = 10
Ninner = 70

Resultlist = c()
Q = c(1:500)
time = seq(0,1000,by = 1)

for (delta.i in deltalist) {
  # delta.i = deltalist[1]
  delta = delta.i
  # 设置存储数据文件名称,参数前缀和取值
  pa.lambda = "ATS1_Lambda0"
  ln = strsplit(as.character(lambda),".",fixed = "T")[[1]][2]
  pa.model = "_Case"
  cn = case.n
  pa.method = "_Zhang"
  pa.delta = "_delta0"
  # delta的参数dn为变量
  dn = strsplit(as.character(delta.i),".",fixed = "T")[[1]][2]
  dir = paste0("E:\\zhangwei\\Rprogram\\In profile monitoring\\busbar ARL data\\",pa.lambda,ln,pa.delta,dn,pa.model,cn,pa.method,".csv")
  
  # 循环并行计算
  print(delta.i)
  for (s in 1:Nouter) {
    start.time = proc.time()
    Result = foreach(1:Ninner, .combine = rbind,.packages = c("MASS")) %dopar% {
      Result = vector("list")
      # 产生数据
      # 失控ATS的delta赋值
      datalist = OCdata.case1(rate = 1,N = 1,tc.end = 1000,delta)
      
      t = datalist$tlist[[1]][Q]
      z = datalist$ylist[[1]][Q]
      x = datalist$xlist[[1]][Q]
      # 数据独立变换
      t = round(as.numeric(t),0);time = round(time,0)
      id = match(t,time)
      # 去除含有固定效应的项，使z变为y
      y = z - x * coef.fixed[id]
      # y的协方差矩阵
      r.matsub = r.mat[id,id]
      y.sigma.sqrt = diag(x) %*% r.matsub %*% t(diag(x)) + diag(sig.sq, nrow(r.matsub))
      lamda.eig <- ginv(eigen(y.sigma.sqrt)$vectors)%*%y.sigma.sqrt%*%(eigen(y.sigma.sqrt)$vectors)
      lambda.sqrt = abs(diag(sqrt(diag(lamda.eig))))
      B = (eigen(y.sigma.sqrt)$vectors)%*%lambda.sqrt%*%solve(eigen(y.sigma.sqrt)$vectors)
      A = solve(B)
      # 独立正态变换
      y.tilde = A %*% y
      x.tilde = A %*% x
      ni = length(y.tilde)
      
      # y.tilde[200:900,] = y.tilde[200:900,]+5
      # acf(y.tilde)
      # t = data.tilde$t
  
      # 估计t时刻的偏移函数delta
      delta.m = delta.func(t,x.tilde,y.tilde)
      # 拟合效果
      y.tilde.fit = x.tilde*delta.m
      # plot(y.tilde,type = "o")
      # lines(y.tilde.fit,col = "red")
      # 统计量的迭代计算
      Hmstat = HmstatFunc(t,x.tilde,y.tilde)
      Hmlist = Hmstat$Hmlist
      # 统计量的期望
      Gmlist = Hmstat$Gmlist
      EHlist = EHfunc(t,x.tilde,Gmlist)
      # 计算方差
      EUUH.list = EUUHfunc(t,x.tilde,Gmlist)
      varALL = varALLfunc(t,x.tilde,Gmlist,EUUH.list)
      Vm.list = varALL$Vm.list
      # 统计量的标准化
      Hmstat = (unlist(Hmlist)-EHlist)/abs(Vm.list)^0.5
      plot(Hmstat,type = "o",cex = 0.3)
      Result = rbind(unlist(Hmlist),EHlist,Hmstat,t[1:length(Hmstat)])
    }
    Resultlist = c(Resultlist,Result)
    write.table(Result,dir,append = TRUE,row.names=FALSE,col.names=FALSE,sep=",")
    end.time = proc.time()
    run.time = (end.time-start.time)/60
    print(s)
    print(run.time)
  }
}

stopImplicitCluster()
```

<!-- 汇总统计量数据 -->
```{r}
delta.i = deltalist[1]
# 设置存储数据文件名称,参数前缀和取值
pa.lambda = "ATS1_Lambda0"
ln = strsplit(as.character(lambda),".",fixed = "T")[[1]][2]
pa.model = "_Case"
cn = case.n
pa.method = "_Zhang"
pa.delta = "_delta0"
# delta的参数dn为变量
dn = strsplit(as.character(delta.i),".",fixed = "T")[[1]][2]
dir = paste0("E:\\zhangwei\\Rprogram\\In profile monitoring\\busbar ARL data\\",pa.lambda,ln,pa.delta,dn,pa.model,cn,pa.method,".csv")


Resultlist =(read.csv(dir,header=F,encoding = "UTF-8"))
Resultlist = as.matrix(Resultlist[,Q])

Resultlist.H =  Resultlist.Hstat = Resultlist.t = c()
N = nrow(Resultlist)/4; N1 = seq(1,4*N,by=4)
j = 1
for (i in N1) {
  Resultlist.H = rbind(Resultlist.H, Resultlist[i,])
  Hstat = abs((Resultlist[i,] - Resultlist[i+1,])/(abs(Resultlist[i+2,]))^0.5)
  Resultlist.Hstat = rbind(Resultlist.Hstat, Hstat) 
  Resultlist.t = rbind(Resultlist.t, Resultlist[i+3,])
  j = j + 1
}

# 计算ATS所需的数据
LRTstat = as.matrix(Resultlist.Hstat[,-(1:30)])
LRT.t = as.matrix(Resultlist.t[,-(1:30)])
LRTstat = as.matrix(LRTstat)
LRT.t = as.matrix(LRT.t)

dimnames(LRTstat)[[2]] = c()
nrows = dim(LRTstat)[1];ncols = dim(LRTstat)[2]

h = 4.396646
# h下的ATS0
RLlist = c()
for (i in 1:(nrows)) {
  index = which(LRTstat[i,]>h)
  if (length(index)==0) {
    RL = LRT.t[i,ncols]
  }
  if (length(index)!=0) {
    RL = LRT.t[i,index[1]]
  }
  RLlist = c(RLlist,RL)
}
round(mean(RLlist),2)
# ATS0的标准差
round(sd(RLlist),2)
```

